from .employee import Employee
from .administrative_employee import AdministrativeEmployee
from .research_employee import ResearchEmployee
from .lecturer import Lecturer
from .dean import Dean
from .project import Project
from .course import Course
from .institute import Institute
from .faculty import Faculty
from .university import University
